on:
  push:
    tags: [ v0.* ]
  pull_request:
    tags: [ v0.* ]



jobs:
  create_release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: create release
        id: r_id
        env:
          GHT: ${{ secrets.GH_TOKEN }}
        run: |
          id=$(curl -q -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GHT" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/perun-cloud-inc/perunctl/releases -d '{"tag_name":"'$GITHUB_REF_NAME'","target_commitish":"main","name":"'$GITHUB_REF_NAME'","body":"Perun Cli New Release","draft":false,"prerelease":false,"generate_release_notes":true}'| jq .id)
          echo $id
          echo "release_id=$id" >> $GITHUB_OUTPUT
    outputs:
      res_id: ${{ steps.r_id.outputs.release_id }}
  
 
  build_cli:
    strategy:
      matrix:
        platforms: ["windows/amd64","windows/386","darwin/amd64","darwin/arm64","linux/amd64","linux/arm64","linux/386"]
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.18.4' # The Go version to download (if necessary) and use.
      - name: build and zip cli
        env:
          GHT: ${{ secrets.GH_TOKEN }}
        run: |
          chmod +x .github/scripts/build_cli.sh
          .github/scripts/build_cli.sh ${{ needs.create_release.outputs.res_id }} ${{ matrix.platforms }}
